# Generated by Django 5.0.6 on 2024-06-03 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Advertisement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('advertisement_name', models.CharField(max_length=100)),
                ('advertisement_pic', models.ImageField(upload_to='advertisement/')),
            ],
        ),
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('movie_name', models.CharField(max_length=100)),
                ('movie_pic', models.ImageField(upload_to='movie/')),
            ],
        ),
        migrations.CreateModel(
            name='Serial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('serial_name', models.CharField(max_length=100)),
                ('serial_pic', models.ImageField(upload_to='serial/')),
            ],
        ),
        migrations.CreateModel(
            name='Web_series',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('web_series_name', models.CharField(max_length=100)),
                ('web_series_pic', models.ImageField(upload_to='web_series/')),
            ],
        ),
    ]
