# Generated by Django 5.0.6 on 2024-06-03 18:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_advertisement_movie_serial_web_series'),
    ]

    operations = [
        migrations.RenameField(
            model_name='movie',
            old_name='movie_pic',
            new_name='image',
        ),
    ]
