# Generated by Django 5.0.6 on 2024-06-03 19:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_rename_movie_pic_movie_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='serial',
            old_name='serial_pic',
            new_name='image',
        ),
    ]
