# Generated by Django 5.0.6 on 2024-06-03 19:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_rename_serial_pic_serial_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='advertisement',
            old_name='advertisement_pic',
            new_name='image',
        ),
        migrations.RenameField(
            model_name='web_series',
            old_name='web_series_pic',
            new_name='image',
        ),
    ]
